name: rabeh
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.5.0+1
  easy_localization: ^3.0.7
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.6
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/svg/
    - assets/lang/


  fonts:
    - family: Somar Rounded
      fonts:
        - asset: assets/fonts/somar_rounded/SomarRounded-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/somar_rounded/SomarRounded-Light.ttf
          weight: 300
        - asset: assets/fonts/somar_rounded/SomarRounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/somar_rounded/SomarRounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/somar_rounded/SomarRounded-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/somar_rounded/SomarRounded-Bold.ttf
          weight: 700
        - asset: assets/fonts/somar_rounded/SomarRounded-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/somar_rounded/SomarRounded-Black.ttf
          weight: 900  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
